### ISSUE TITLE
Feature: support video recordings

### ISSUE THREAD

**Issue by lblanch** [lblanch/trail-camera#1]
Integrate videos to the app so they can be seen alongside pictures.

- [ ] Generate thumbnail version of video #2 
- [ ] Show videos on dashboard with autoplay #3 
- [ ] Show video on recording page with controls #4 
- [ ] Update db seeding script to include videos #12

**Comment by lblanch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [support video](https://trello.com/c/8maab4Xa/135-support-video)
